package com.aicontentgenerator.ai.client;


import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;

/**
 * Mock AI provider — active by default (app.ai.provider=mock).
 *
 * Returns a predictable, human-readable response so all other modules
 * (content, scheduler) can be developed and tested without an API key.
 *
 * To switch to real OpenAI:
 *   export AI_PROVIDER=openai
 *   export OPENAI_API_KEY=sk-...
 */
@Component
@ConditionalOnProperty(name = "app.ai.provider", havingValue = "mock", matchIfMissing = true)
@Slf4j
public class MockAiProviderClient implements AiProviderClient {

    @Override
    public String generate(String prompt) {
        log.info("[MOCK AI] Generating content for prompt: \"{}\"", prompt);

        return buildMockResponse(prompt);
    }

    private String buildMockResponse(String prompt) {
        return String.format(
                """
                [MOCK RESPONSE — %s]
                
                You asked about: "%s"
                
                This is a placeholder response generated by the mock AI provider.
                In production, this would be replaced with real AI-generated content
                from your configured provider (e.g., OpenAI GPT-4o-mini).
                
                To enable real AI generation, set:
                  AI_PROVIDER=openai
                  OPENAI_API_KEY=sk-...
                """,
                LocalDateTime.now(),
                prompt
        );
    }
}